apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    db: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      db: redis
  template:
    metadata:
      labels:
        db: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    db: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
