apiVersion: v1
kind: Service
metadata:
  name: app-pedido-service
spec:
  selector:
    app: pedido
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31302
  type: LoadBalancer
